### PR TITLE
Automatic version update in WallGoMatrix Mathematica

### PR DESCRIPTION
**Pull request by pschicho**
Added a small sed script to update the version number via a commit when tagging a version. However, this seems to fail so far.

### CODE REVIEW

**Comment by og113** [comment]
Nice work.

Given this isn't working, let me just suggest an alternative approach, which might be simpler even if less automatic:
- the GitHub workflow grabs the version number from the Mathematica file
- it then compares the version number against the current tag and throws an error if they differ
```
if [ "$WallGoMatrixVersion" == "${{ github.ref_name }}" ]; then
    echo "Error: $WallGoMatrixVersion does not match tag" 1>&2
    exit 64
fi
```
So, you would then have to update $WallGoMatrixVersion by hand, to make sure it agrees with the git tag. It's not perfect, but it would prevent different versions appearing in different places.

**Comment by pschicho** [comment]
> Nice work.
> 
> Given this isn't working, let me just suggest an alternative approach, which might be simpler even if less automatic:
> 
> * the GitHub workflow grabs the version number from the Mathematica file
> * it then compares the version number against the current tag and throws an error if they differ
> 
> ```
> if [ "$WallGoMatrixVersion" == "${{ github.ref_name }}" ]; then
>     echo "Error: $WallGoMatrixVersion does not match tag" 1>&2
>     exit 64
> fi
> ```
> 
> So, you would then have to update $WallGoMatrixVersion by hand, to make sure it agrees with the git tag. It's not perfect, but it would prevent different versions appearing in different places.

Where would this have to placed? I would still have to extract $WallGoMatrixVersion from somewhere?

Could it be that it failed because it's not on main. It fails for me because of a detached head it seems.

**Comment by og113** [comment]
I was just writing the above as a vague pointer as to how to throw an error in bash. Yes, you would have to extract $WallGoMatrixVersion from the Mathematica file.

As regards the original approach, one small issue I realised is that a tag is associated to a specific commit, so if the version number is updated on a different commit, then the version and tag don't quite line up. Maybe not a big deal.

**Comment by pschicho** [comment]
> I was just writing the above as a vague pointer as to how to throw an error in bash. Yes, you would have to extract $WallGoMatrixVersion from the Mathematica file.

This works now. 

> As regards the original approach, one small issue I realised is that a tag is associated to a specific commit, so if the version number is updated on a different commit, then the version and tag don't quite line up. Maybe not a big deal.

However, automatic version number updating is more complicated and would require some book keeping of future and past version numbers. But using tags to trigger the updating the tag will come with the old version number and trigger the update in the code and push it. This way the release would have the right version number in the zipped files but then the tag itself has outdated version number. I decided to comment and abandon this for now and just go with the failing release action via the if statements in bash.

**Pull request merged**
