### PR TITLE
Paclet info

### PR DESCRIPTION
**Pull request by pschicho**
-add information in case paclet packaging is desired at some point.
-add command line parsing for --outputFile. This is useful for integrated use with wallgo python
-add version number (should be updated automatically in the future)

### CODE REVIEW

**Review by og113 — CHANGES_REQUESTED** [review]
Nice work. Given you have moved WallGoMatrix.m in this PR, it will fail to be included in the automatic GitHub release, which currently only includes the contents of src. The same is true of the new PacletInfo.m and init.m. How should all these files be packaged up in the release .zip files?

**Comment by pschicho** [comment]
> Nice work. Given you have moved WallGoMatrix.m in this PR, it will fail to be included in the automatic GitHub release, which currently only includes the contents of src. The same is true of the new PacletInfo.m and init.m. How should all these files be packaged up in the release .zip files?

The packaging should be similar to the current file structure. For now, I think it is enough to package `WallGoMatrix.m + \src`.

**Review by og113 — CHANGES_REQUESTED** [review]
All makes sense.
- Can you merge main into this branch?
- Have you tested that the new release set up works?

**Comment by pschicho** [comment]
I merged main here and adapted the packaging. However, I could not manage to get both the `WallGoMatrix.m` and `src/` inside the packaging folder either one of them ends up not being packaged when `cp` the folders/file.

**Comment by pschicho** [comment]
> All makes sense.
> 
> * Can you merge main into this branch?
> * Have you tested that the new release set up works?

This is all fixed now.

**Review by og113 — APPROVED** [review]
I've tested the new release and importing it. Nice work :)

**Pull request merged**
