### PR TITLE
Command line convenience

### PR DESCRIPTION
**Pull request by pschicho**
Plans for this PR

- remove verbose output when running via `wolframscript` on the command line
- give better error messages when packages fail to load

### CODE REVIEW

**Comment by og113** [comment]
Didn't seem to work for me. I ran
```
wolframscript -file 'qcd.m'
```
and got the following output
```
Grid[{{-Image-, GOGOGOGOGOGOGOGOGOGOGOGO WallGoMatrix GOGOGOGOGOGOGOGOGOGOGGOGOGO
Version: 0.1.1 (09-10-2024)
Authors: Hyperlink[Andreas Ekstedt, https://inspirehep.net/authors/1799400], Hyperlink[Oliver Gould, https://inspirehep.net/authors/1606373], Hyperlink[Joonas Hirvonen, https://inspirehep.net/authors/1866901], Hyperlink[Benoit Laurent, https://inspirehep.net/authors/1808372], Hyperlink[Lauri Niemi, https://inspirehep.net/authors/1764675], Hyperlink[Philipp Schicho, https://inspirehep.net/authors/1639147], Hyperlink[Jorinde van de Vis, https://inspirehep.net/authors/1589979]
Reference: Hyperlink[2410.xxxxx [hep-ph], https://arxiv.org/abs/2410.xxxxx]
Repository link: Hyperlink[Mouseover[github.com/Wall-Go/WallGoMatrix, github.com/Wall-Go/WallGoMatrix], https://github.com/DR-algo/DRalgo]
Existing model files: Hyperlink[Mouseover[WallGoMatrix/examples, WallGoMatrix/examples], https://github.com/Wall-Go/WallGoMatrix/tree/main/examples]
GOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGOGGOGOGOGOGOGOGOGO}}, Alignment -> {Left, Center}]
Grid[{{Hyperlink[Mouseover[-Image-, -Image-], paclet:GroupMath/tutorial/GroupMathDoc], XXXXXXXXXXXXXXXXXXXXXXXXXXX GroupMath XXXXXXXXXXXXXXXXXXXXXXXXXX
Version: 1.1.2 (6/May/2020)
Author: Renato Fonseca
Reference: 2011.01764 [hep-th]
Website: Hyperlink[Mouseover[renatofonseca.net/groupmath, renatofonseca.net/groupmath], http://renatofonseca.net/groupmath]
Built-in documentation: Hyperlink[Mouseover[here, here], paclet:GroupMath/tutorial/GroupMathDoc]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}}, Alignment -> {Left, Center}]

SetDelayed::write: Tag BlockDiagonalMatrix in BlockDiagonalMatrix[blocks_] is Protected.
GroupMath is an independent package, and is not part of WallGoMatrix
Please cite GroupMath: Comput.Phys.Commun. 267 (2021) 108085 • e-Print: DisplayForm[TemplateBox[{RowBox[{2011.01764,  , [, RowBox[{hep, -, th}], ]}], {URL[https://arxiv.org/abs/2011.01764], None}, https://arxiv.org/abs/2011.01764, HyperlinkActionRecycled, {HyperlinkActive}, BaseStyle -> {Hyperlink}, HyperlinkAction -> Recycled}, HyperlinkTemplate]]
WallGoMatrix is powered by the DRalgo ModelCreation.
Please cite DisplayForm[TemplateBox[{DRalgo, {URL[https://github.com/DR-algo/DRalgo], None}, https://github.com/DR-algo/DRalgo, HyperlinkActionRecycled, {HyperlinkActive}, BaseStyle -> {Hyperlink}, HyperlinkAction -> Recycled}, HyperlinkTemplate]]: Comput.Phys.Commun. 288 (2023) 108725 • e-Print: DisplayForm[TemplateBox[{RowBox[{2205.08815,  , [, RowBox[{hep, -, ph}], ]}], {URL[https://arxiv.org/abs/2205.08815], None}, https://arxiv.org/abs/2205.08815, HyperlinkActionRecycled, {HyperlinkActive}, BaseStyle -> {Hyperlink}, HyperlinkAction -> Recycled}, HyperlinkTemplate]]

Get::noopen: Cannot open /Users/ogould/Library/WolframEngine/Applications/WallGoMatrix/src/modelCreation.m.

Get::noopen: Cannot open /Users/ogould/Library/WolframEngine/Applications/WallGoMatrix/src/matrixElements.m.

Set::shape: Lists {gvvv, gvff, gvss, λ1, λ3, λ4, μij, μIJ, μIJC, Ysff, YsffC} and AllocateTensors[{SU3}, {{1, 1}}, {gs}, {{{{1, 0}}, L}, {{{1, 0}}, R}, {{{1, 0}}, L}, {{{1, 0}}, R}, {{{1, 0}}, L}, {{{1, 0}}, R}, {{{1, 0}}, L}, {{{1, 0}}, R}, {{{1, 0}}, L}, {{{1, 0}}, R}, {{{1, 0}}, L}, {{{1, 0}}, R}}, {}] are not the same shape.

SparseArray::list: List expected at position 1 in SparseArray[μij].

SparseArray::list: List expected at position 1 in SparseArray[gvvv].

SparseArray::list: List expected at position 1 in SparseArray[gvss].

General::stop: Further output of SparseArray::list will be suppressed during this calculation.

Part::partd: Part specification gvff[[1]] is longer than depth of object.

Table::iterb: Iterator {WallGoMatrix`Private`i, WallGoMatrix`Private`MatrixElements} does not have appropriate bounds.

Table::iterb: Iterator {WallGoMatrix`Private`i, WallGoMatrix`Private`MatrixElements} does not have appropriate bounds.

Table::nliter: Non-list iterator (Association[externalParticles -> #1[[1]] /. WallGoMatrix`Private`M[GroupMath`a__] -> {GroupMath`a}, parameters -> WallGoMatrix`Private`toString$3202 /@ WallGoMatrix`Private`getRelevantParameters$3202[#1[[2]]], expression -> WallGoMatrix`Private`replaceSpecials$3202[WallGoMatrix`Private`toString$3202[WallGoMatrix`Private`PrintNonPrivate[#1[[2]]]]]] & )[{WallGoMatrix`Private`i, WallGoMatrix`Private`MatrixElements}] at position 2 does not evaluate to a real numeric value.

Export::jsonstrictencoding: Expression Table cannot be exported as JSON.
Results have been exported to: output/matrixElements.qcd.json

Table::iterb: Iterator {WallGoMatrix`Private`i, WallGoMatrix`Private`MatrixElements} does not have appropriate bounds.

General::stop: Further output of Table::iterb will be suppressed during this calculation.

Table::nliter: Non-list iterator (WallGoMatrix`Private`toString[WallGoMatrix`Private`PrintNonPrivate[#1[[1]]]]<> -> <>WallGoMatrix`Private`replaceSpecials[WallGoMatrix`Private`toString[WallGoMatrix`Private`PrintNonPrivate[#1[[2]]]]] & )[{WallGoMatrix`Private`i, WallGoMatrix`Private`MatrixElements}] at position 2 does not evaluate to a real numeric value.

Part::partd: Part specification WallGoMatrix`Private`i[[2]] is longer than depth of object.

Part::partw: Part 3 of WallGoMatrix`Private`i[[2]] does not exist.

Part::partw: Part 4 of WallGoMatrix`Private`i[[2]] does not exist.

Part::partd: Part specification WallGoMatrix`Private`i[[1]] is longer than depth of object.

General::stop: Further output of Part::partd will be suppressed during this calculation.

Part::partw: Part 3 of i[[2]] does not exist.

General::stop: Further output of Part::partw will be suppressed during this calculation.

Table::nliter: Non-list iterator (WallGoMatrix`Private`toString[WallGoMatrix`Private`PrintNonPrivate[#1[[1]]]]<> -> <>WallGoMatrix`Private`replaceSpecials[WallGoMatrix`Private`toString[WallGoMatrix`Private`PrintNonPrivate[#1[[2]]]]] & )[WallGoMatrix`Private`MatrixElemToC[WallGoMatrix`Private`i] //. OptionValue[ExportMatrixElements, {{TruncateAtLeadingLog -> True, Format -> {json, txt}}}, WallGoMatrix`Private`Replacements]] at position 2 does not evaluate to a real numeric value.

General::stop: Further output of Table::nliter will be suppressed during this calculation.
Results have been exported to: output/matrixElements.qcd.txt
TerminatedEvaluation[RecursionLimit]
$RecursionLimit::reclim: Recursion depth of 1024 exceeded.
```

**Comment by og113** [comment]
I guess some of these `GOGOGO` things and `Hyperlink[Mouseover` should probably be dropped for the command line.

**Comment by pschicho** [comment]
> I guess some of these `GOGOGO` things and `Hyperlink[Mouseover` should probably be dropped for the command line.

That is strange. This branch actually removed the command line verbose prints. Did you clone just this branch to your `$UserBaseDirectory` or did you update the `WallGoMatrix` folder inside `$UserBaseDirectory`?

**Comment by og113** [comment]
My mistake! I can copied over the version on `main` by accident. It works on this branch.

**Review by og113 — APPROVED** [review]

**Review by og113 — APPROVED** [review]

**Pull request merged**
